- name: Install pipenv
  pip:
    name: pipenv
    executable: "{{ 'pip' if (python_version|int == 2) else 'pip3' }}"
  become: yes

# We need to ensure that pipenv uses up-to-date versions of setuptools and pip
- name: Make sure pipenv uses correct versions of pip and setuptools
  command: pipenv run -- pip install pip=={{ pip_version }} setuptools=={{ setuptools_version }}

- name: Run pipenv install
  command: pipenv install --dev

- name: Retrieve venv root
  shell: pipenv --venv
  register: env_root_output

- set_fact:
    env_root={{ env_root_output.stdout }}

- name: Activate virtualenv when sshing into the box
  lineinfile:
    dest: ~/.bashrc
    regexp: '^\. .*/bin/activate$'
    line: '. {{ env_root }}/bin/activate'

- name: Let pipenv know it can manage this virtualenv
  lineinfile: dest=~/.bashrc line='export PIPENV_ACTIVE=1'
