---
# Actual installation is done in the 'virtualenv' role

# This role requires either the postgresql or mysql roles to be enabled
# Please note that Python 3 compatibility is only supported since jessie

# Gettext is used by Django's compilemessages
- name: ensure gettext is installed
  apt: pkg=gettext state=latest
  become: yes

- name: create the local environement directory
  file: path={{ django_root }}/envdir state=directory

- name: fill in DATABASE_URL setting
  copy: "dest={{ django_root }}/envdir/DATABASE_URL content={{ database_type }}://{{ database_user }}:{{ database_user }}@localhost/{{ database_name }}"
  when: database_type is defined

- name: fill in ALLOWED_HOSTS setting
  template:
    src: allowed_hosts.j2
    dest: "{{ django_root }}/envdir/ALLOWED_HOSTS"

- name: migrate
  command: "{{ env_root }}/bin/python {{ django_root }}/manage.py migrate --noinput"
  when: database_type is defined and not django_use_pipenv

- name: migrate
  command: "pipenv run {{ django_root }}/manage.py migrate --noinput"
  when: database_type is defined and django_use_pipenv

- name: download Django bash completion file
  get_url:
    url: https://raw.githubusercontent.com/django/django/master/extras/django_bash_completion
    dest: ~/.django_bash_completion

- name: enable Django bash completion
  lineinfile: dest=~/.bashrc line='. ~/.django_bash_completion'
